---
openapi: 3.0.0
info:
  title: Tastify
  description: A music taste analysis and comparison tool
  contact:
    email: hello@ryancarr.ca
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ryandougc/Tastify/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /user:
    post:
      summary: creates a new user profile
      description: Adds a user to the system
      operationId: createUser
      requestBody:
        description: User to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        "201":
          description: user created
        "400":
          description: "invalid input, object invalid"
        "409":
          description: an existing user already exists
  /user/{profileId}:
    get:
      summary: searches inventory
      description: "By passing the profileId of the user you want data for, you can retrieve the corresponding profile object for that user"
      operationId: searchUsers
      parameters:
      - name: profileId
        in: path
        description: pass the required profileId to look up the user
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: user profile matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Profile'
              example:
                NoAnalysisData:
                  value:
                    profileId: e09af884-3ab9-4c19-9672-3b92e22faf32
                    spotifyUsername: username12
                    dateCreated: "1679713086246"
                    genres: []
                HasAnalysisData:
                  value:
                    profileId: 37c793eb-6390-49b1-8cb5-f4df175bb980
                    spotifyUsername: username305
                    dateCreated: "1679713164062"
                    genres:
                    - name: country
                      coun t: 3
                      tracks:
                      - track:
                          artists:
                          - genres:
                            - Contemporary Country
                            - Country
                            href: https://api.spotify.com/v1/artists/718COspgdWOnwOFpJHRZHS
                            id: 718COspgdWOnwOFpJHRZHS
                            name: Luke Combs
                            popularity: 85
                          href: https://api.spotify.com/v1/tracks/7aEtlGHoiPAfRB084NiDmx
                          id: 7aEtlGHoiPAfRB084NiDmx
                          name: Beer Never Broke My Heart
                          type: track
                        count: 1
                      - track:
                          artists:
                            genres:
                            - Contemporary Country
                            - Outlaw Country
                            href: https://api.spotify.com/v1/artists/4YLtscXsxbVgi031ovDDdh
                            id: 4YLtscXsxbVgi031ovDDdh
                            name: Chris Stapleton
                            popularity: 81
                          href: https://api.spotify.com/v1/albums/7lxHnls3yQNl8B9bILmHj7
                          id: 3fqwjXwUGN6vbzIwvyFMhx
                          name: Tennessee Whiskey
                          type: track
                        count: 1
                      - track:
                          artists:
                          - genres:
                            - Contemporary Country
                            - Country
                            href: https://api.spotify.com/v1/artists/718COspgdWOnwOFpJHRZHS
                            id: 718COspgdWOnwOFpJHRZHS
                            name: Luke Combs
                            popularity: 85
                          href: https://api.spotify.com/v1/tracks/1mMLMZYXkMueg65jRRWG1l
                          id: 1mMLMZYXkMueg65jRRWG1l
                          name: When It Rains It Pours
                          type: track
                        count: 1
                      artists:
                      - artist:
                          genres:
                          - Contemporary Country
                          - Country
                          href: https://api.spotify.com/v1/artists/718COspgdWOnwOFpJHRZHS
                          id: 718COspgdWOnwOFpJHRZHS
                          name: Luke Combs
                          popularity: 85
                        count: 2
                      - artist:
                          genres:
                          - Contemporary Country
                          - Outlaw Country
                          href: https://api.spotify.com/v1/artists/4YLtscXsxbVgi031ovDDdh
                          id: 4YLtscXsxbVgi031ovDDdh
                          name: Chris Stapleton
                          popularity: 81
                        count: 1
                    - name: hip hop
                      count: 1
                      tracks:
                      - track:
                          artists:
                          - ""
                          type: track
                        count: 1
                      artists:
                      - artist:
                          genres:
                          - hip hop
                          popularity: 1
                        count: 1
        "400":
          description: bad input parameter
        "404":
          description: user doesn't exist
components:
  schemas:
    Profile:
      required:
      - profileId
      - spotifyUsername
      type: object
      properties:
        profileId:
          type: integer
          format: int64
        spotifyUsername:
          type: string
        dateCreated:
          type: string
        genres:
          type: array
          items:
            $ref: '#/components/schemas/Analysis'
    Analysis:
      type: object
      properties:
        name:
          type: string
        count:
          type: integer
          format: int64
        tracks:
          type: array
          items:
            $ref: '#/components/schemas/TrackEntry'
        artists:
          type: array
          items:
            $ref: '#/components/schemas/ArtistEntry'
      description: A user's profile
    Artist:
      type: object
      properties:
        genres:
          type: array
          items:
            type: string
        href:
          type: string
        id:
          type: string
        name:
          type: string
        popularity:
          type: integer
          format: int64
    ArtistEntry:
      type: object
      properties:
        artist:
          $ref: '#/components/schemas/Artist'
        count:
          type: integer
          format: int64
    Track:
      type: object
      properties:
        artists:
          type: array
          items:
            $ref: '#/components/schemas/Artist'
        href:
          type: string
        id:
          type: string
        name:
          type: string
        type:
          type: string
          enum:
          - track
    TrackEntry:
      type: object
      properties:
        track:
          $ref: '#/components/schemas/Track'
        count:
          type: integer
          format: int64
